baseurl = "https://bigboarbearbaits.com" 
title = "Big Boar Bear Baits"
theme = "universal"
languageCode = "en-us"
defaultContentLanguage = "en"

# Define the number of posts per page
[params.pagination]
    pagerSize = 25

# Main menu
[menu]
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Products"
    identifier = "menu.products"
    url        = "/products/"
    weight     = 2

    [[menu.main]]
        name       = "All Products"
        identifier = "products.all"
        url        = "/products"
        weight     = 1
        parent     = "menu.products"

    [[menu.main]]
        name       = "Trail Mixes"
        url        = "/categories/trail-mixes/"
        weight     = 1
        parent     = "menu.products"

    [[menu.main]]
        name       = "Attractants"
        url        = "/"
        weight     = 2
        parent     = "menu.products"

    [[menu.main]]
        name       = "Spreads"
        url        = "/categories/spreads/"
        weight     = 3
        parent     = "menu.products"

    [[menu.main]]
        name       = "Fillings"
        url        = "/categories/fillings/"
        weight     = 4
        parent     = "menu.products"

    [[menu.main]]
        name       = "Extras"
        url        = "/"
        weight     = 5
        parent     = "menu.products"

[[menu.main]]
    name       = "Contact"
    identifier = "menu.contact"
    url        = "/contact"
    weight     = 3

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/profile.php?id=61558801570967"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:bigboarbearbaits@outlook.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/products/"
    author = "DevCows"
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["products"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = true
    logo_text = "Big Boar Bear Baits"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"

[permalinks]
    blog = "/products/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false

# Enable and disable widgets for the right sidebar in the blog
[params.widgets]
    categories = true
    tags = false
    search = true

[params.carouselHomepage]
 enable = true

[params.see_more]
    enable = true
    icon = "fa fa-tree"
    title = "The Panhandle's premium bear bait distributor"
    subtitle = "Are you as passionate as we are about baiting and hunting bears?"

[params.testimonials]
    enable = false
    title = "filler"

[params.recent_posts]
    enable = true
    title = ""
    subtitle = "If so, look no further for all your baiting needs."
    content = "We work in close partnership with Kingpin to provider our customers with the best quality and selection."
    hide_summary = false

# number of words of summarized post content (default 70)
summaryLength = 15

[params.footer.recent_posts]
    enable = false

[taxonomies]
    category = "categories"
    tag = "tags"
